### ISSUE TITLE
Cheat not loading on Firefox

### ISSUE THREAD

**Issue by Tek56** [myerffoeg/popsauce#2]
I couldn't install it on Tampermonkey so I went on Greasemonkey.
Greasemonkey is activated, the Script is installed and activated on http://popsauce.sparklinlabs.com/*, i'm pressing the ² key but there are no reaction at all.

**Comment by myerffoeg** [comment]
Hello,
when you come in a room you must press ², this cheat is working only on french dictionary, when the answer is found it will show it here (you can click on it to answer it directly) :

![image](https://user-images.githubusercontent.com/20592783/73497032-1f84db00-43ba-11ea-9064-711eec62b40e.png)

Otherwise, it will show nothing ; when the challenge ends it will save the answer locally until you delete your web browser cache.

If you still cannot make it works please provide me your console output (CTRL + MAJ + i on Chrome or F12 on Firefox) thank you.

**Comment by Tek56** [comment]
Hi,

It now works perfectly on Chrome (Even though when i copied the .js file, it showed me a lot of errors due to the variable '$'). So thanks a lot!

On Firefox, there is still some problem.
Here is what shows my console output :
<img width="309" alt="1" src="https://user-images.githubusercontent.com/43536138/73499452-6d044680-43c0-11ea-9d7c-7ca844a35841.png">

I've looked within my settings and even if I add the link of popsauce to the exceptions here : 
<img width="590" alt="2" src="https://user-images.githubusercontent.com/43536138/73499537-a341c600-43c0-11ea-9d8a-14c236c6d081.png">
It's not working (Firefox).

Thanks for your time

**Comment by myerffoeg** [comment]
Great. 

The $ variable is the jQuery library used to interact with the DOM, the metadata @require should import crypto-js and jQuery. Actually it looks like Firefox is not allowing the crypto-js to be imported thus causing the current error or maybe Firefox is not allowing Greasemonke to access the main frame.

I'll look deeper into this issue on Firefox and hopefully fix it soon.

**Comment by myerffoeg** [comment]
After a deeper look it seems that Greasemonkey eval the code in a sandbox and thus cannot access the top frame variables but it can be fixed. I will do it this afternoon have a nice day.

**Comment by myerffoeg** [comment]
So I've looked into Greasemonkey documentation & it seems that using content page variables is not recommended as well as unsafe : https://wiki.greasespot.net/UnsafeWindow .

Even with the `unsafeWindow` the userscript cannot emit any socket messages since it cannot access the userscript's methods (throwing a permission denied exception). There may be a work around setting a method in the `unsafeWindow` but I will not do it for obvious security, compatibility as well as code clarity reasons.

**So for now I'll drop Firefox support until I find a better solution.**
